### ISSUE TITLE
Hybrid Cloud

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#129]
- [x] **the same text in blocks on the layout (on desktop and mobile, respectively)**

![the same text in blocks.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/8fcb9cd2-89b1-4d21-9ee9-8608bf9a0bc7)
____________________________________________________________________________________________________

- [x] **change the color of the elements to match the one on the layout (desktop and mob)**
### 
 **_EXPECTED RES_**
![change color(mob)layout.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/82e892cc-65fd-4988-8477-71cc19f73f35)

### **_ACTUAL RES_**
![change color(mob).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/65bb5fd6-ea4a-4b53-bac5-0d8cd3fabca5)
![change color.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d9f1b76d-2288-4d9f-acb9-4f895f4ace40)
___________________________________________________________________________________________________

- [x] **on IPhone 12pro / IPhone SE the block with the text partially overlaps**

![iphone SE.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/7c39de9c-0ba8-4018-a265-7fb9f2abfbd1)

![iphone 12pro.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c247f1cb-1411-4a33-abe8-2257fc881024)

__________________________________________________________________________-

- [x]  **the picture covers the button**
![hybrid_cloud.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/4976f0ec-cc17-49fd-bbb2-416eee1b91e1)

**Comment by ghostring31** [comment]
Security text

There are countless concerns about data breaches in every industry. Security is the most essential part of a network for most companies. Data breaches can create devastating effects for businesses and their customers alike. Post-securing breaches could leave a tinge of mistrust in the air.
Cloud security is essential to all parts of businesses because it affects many parts of all operations.
Consider the needs of your digital security. When you have a hybrid cloud, you get the benefits of a public cloud and the security of a private one. Building hybrid architecture we're using our experience and security best practices to protect your data.

**Comment by Natali-Oliinyk-qa** [comment]
- [x]  when navigating to the Name and Email fields, "Call me back " button is sliding (desktop)
![sliding button.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/66a01407-5828-4d74-9ac4-359f3275a40b)

**Comment by ghostring31** [comment]
Security text should be 

There are countless concerns about data breaches in every industry. Security is the most essential part of a network for most companies. Data breaches can create devastating effects for businesses and their customers alike. Post-securing breaches could leave a tinge of mistrust in the air.
Cloud security is essential to all parts of businesses because it affects many parts of all operations.
When you have a hybrid cloud, you get the benefits of a public cloud and the security of a private one. Considering the needs of your digital security we use security best practices in our work.

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] the button is cut off (768-1023)
![button1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/5fb84bd9-18a5-459f-8d93-e5871be60aae)
